name: async_locks
description: Synchronization primitives for asynchronous Dart code, inspired from Python
version: 1.0.0
homepage: https://github.com/Serious-senpai/async-locks

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
