name: async_locks
version: 4.0.2
description: "Synchronization primitives for asynchronous Dart code: Event, Lock and Semaphore"
homepage: https://github.com/Serious-senpai/async-locks
repository: https://github.com/Serious-senpai/async-locks
issue_tracker: https://github.com/Serious-senpai/async-locks/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.25.2

topics:
  - async
  - concurrency
  - lock
  - mutex
