name: async_locks
description: Synchronization primitives for asynchronous Dart code, inspired from Python
version: 2.0.0
homepage: https://github.com/Serious-senpai/async-locks
repository: https://github.com/Serious-senpai/async-locks

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.22.1
