name: async_locks
description: Synchronization primitives for asynchronous Dart code, inspired from Python
version: 3.3.2
homepage: https://github.com/Serious-senpai/async-locks
repository: https://github.com/Serious-senpai/async-locks
issue_tracker: https://github.com/Serious-senpai/async-locks/issues

environment:
  sdk: ">=2.18.1 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
