name: async_locks
description: Synchronization primitives for asynchronous Dart code, inspired from Python
version: 3.3.3
homepage: https://github.com/Serious-senpai/async-locks
repository: https://github.com/Serious-senpai/async-locks
issue_tracker: https://github.com/Serious-senpai/async-locks/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
