name: Package test

on: push

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1.7.1

    - name: Install dependencies
      run: dart pub get

    - name: Analyze package
      run: dart analyze

    - name: Run package tests
      run: dart test --concurrency=3 --reporter=github test
