name: Package Test

on: push

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Run package tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        sdk: [2.18.7, 2.19.1]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1.3
      with:
        sdk: ${{ matrix.sdk }}

    - name: Install dependencies
      run: dart pub get

    - name: Analyze package
      run: dart analyze

    - name: Run package tests
      run: dart test --concurrency=3 --reporter=github test
